import java.io.*;
import java.util.*;
//Yonatan Shimroni
/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

public class P2
{
	public static int makeFib(int upperBound)
	{	int fib1 = 1;
		int fib2 = 2;
		int fib = 0;
		int sum = 0;
		while (sum < upperBound)
		{
			fib = fib1 + fib2;
			fib1 = fib2;
			fib2 = fib;
			if (fib % 2 ==0)
			{
				sum += fib;
			}
		}
		return sum + 2; //2 is added since it is not checked at the begeining
	}
	public static void main(String[] args)
	{
		int sum = 0;
		System.out.println("Sum is: " + makeFib(Integer.parseInt(args[0])));
	}
}